"""Per-install identity helpers (TKT-0031).

`WATIFY_APP_SECRET` and `WATIFY_API_KEY` are generated by
`install/install.sh` via `openssl rand -hex 32` on a fresh install and
preserved across re-runs. Their values must never appear in logs,
ticket bodies, conversation transcripts, or anywhere else outside the
backend's `.env` file and process memory.

This module provides:
- `is_configured()` -- True iff `app_secret` is set (auth is operable).
- `fingerprint()` -- first 8 hex chars of `sha256(app_secret)`. Safe to
  surface in /api/health so an operator can verify two boxes share the
  same secret without seeing it. Returns `None` when unconfigured.
"""

from __future__ import annotations

import hashlib
import secrets

from app.settings import settings


def is_configured() -> bool:
    """Auth + cookie signing requires app_secret. Other features (groups,
    jobs, wars connect) run fine without it."""
    return bool(settings.app_secret)


def fingerprint() -> str | None:
    """Stable, non-reversible identifier for the current app_secret.

    Returns None when `app_secret` is unset. Operators can compare
    fingerprints across hosts to confirm they share a secret without
    transmitting the secret itself.
    """
    if not settings.app_secret:
        return None
    return hashlib.sha256(settings.app_secret.encode("utf-8")).hexdigest()[:8]


def generate_secret_hex(nbytes: int = 32) -> str:
    """Generate a fresh `openssl rand -hex 32` equivalent. Used by
    install.sh's Python-side helpers and as the canonical generator
    referenced by `.env.example`."""
    return secrets.token_hex(nbytes)


def api_key_matches(provided: str) -> bool:
    """Constant-time compare of a presented API key against the
    installed value. Returns False when api_key is unset (so misconfig
    fails closed, never grants access)."""
    if not settings.api_key or not provided:
        return False
    return secrets.compare_digest(provided, settings.api_key)
